export const carBrands = {
    mainstream: [
      "Toyota",
      "Honda",
      "Ford",
      "Chevrolet",
      "Nissan",
      "Hyundai",
      "Kia",
      "Volkswagen",
      "Subaru",
      "Mazda",
      "Mitsubishi",
      "Peugeot",
      "Renault",
      "Fiat",
      "Skoda",
      "Suzuki",
      "Citroën",
      "Opel",
      "Vauxhall",
      "SEAT",
    ],
    luxury: [
      "Mercedes-Benz",
      "BMW",
      "Audi",
      "Lexus",
      "Jaguar",
      "Land Rover",
      "Cadillac",
      "Lincoln",
      "Volvo",
      "Porsche",
      "Infiniti",
      "Genesis",
      "Acura",
      "Alfa Romeo",
      "Maserati",
      "Bentley",
      "Rolls-Royce",
      "Aston Martin",
      "Ferrari",
      "Lamborghini",
    ],
    electric: [
      "Tesla",
      "Rivian",
      "Lucid",
      "Polestar",
      "NIO",
      "Xpeng",
      "BYD",
      "Fisker",
      "Canoo",
      "Lordstown Motors",
    ],
    supercar: [
      "Ferrari",
      "Lamborghini",
      "McLaren",
      "Bugatti",
      "Pagani",
      "Koenigsegg",
      "Aston Martin",
      "Rimac",
      "SSC North America",
    ],
    commercial: [
      "Ford",
      "Ram",
      "Chevrolet",
      "GMC",
      "Isuzu",
      "Iveco",
      "MAN",
      "Scania",
      "Freightliner",
      "Kenworth",
    ],
    regional: [
      "Tata Motors",
      "Mahindra",
      "Great Wall Motors",
      "Geely",
      "Chery",
      "Proton",
      "Perodua",
      "Dacia",
      "Lada",
      "UAZ",
    ],
    defunct: [
      "Saab",
      "Pontiac",
      "Saturn",
      "Oldsmobile",
      "Hummer",
      "Plymouth",
      "Mercury",
      "Scion",
      "Daewoo",
      "Studebaker",
    ],
  };