export const carFeatures: string[] = [
    "Air Conditioning",
    "Leather Seats",
    "Sunroof",
    "Navigation System",
    "Bluetooth",
    "Cruise Control",
    "Adaptive Cruise Control",
    "Lane Departure Warning",
    "Blind Spot Monitoring",
    "Automatic Emergency Braking",
    "Parking Sensors",
    "Rearview Camera",
    "Apple CarPlay",
    "Android Auto",
    "Satellite Radio",
    "Keyless Entry",
    "Push Button Start",
    "Heated Seats",
    "Ventilated Seats",
    "Power Seats",
    "Memory Seats",
    "Panoramic Sunroof",
    "Surround View Camera",
    "Heads-Up Display",
    "Wireless Charging",
    "Navigation with Real-Time Traffic",
    "Premium Audio System",
    "Remote Start",
    "Remote Lock/Unlock",
    "Adaptive Headlights",
    "Power Liftgate",
    "Power Windows",
    "Power Mirrors",
    "Dual-Zone Climate Control",
    "Triple-Zone Climate Control",
    "Ambient Lighting",
    "Leather-Wrapped Steering Wheel",
    "Heated Steering Wheel",
    "Automatic High Beams",
    "Hill Start Assist",
    "Traction Control",
    "Stability Control",
    "Rear Cross Traffic Alert",
    "Front Collision Warning",
    "Pedestrian Detection",
    "Rear Window Defroster",
    "Auto-Dimming Rearview Mirror",
    "Rain-Sensing Wipers",
    "Blind Spot Intervention",
    "Cross Traffic Alert",
    "Adaptive Suspension",
    "Sport Mode",
    "Eco Mode",
    "Tow Hitch",
    "All-Wheel Drive",
    "Four-Wheel Drive",
    "Advanced Driver Assistance System (ADAS)",
    "Emergency Roadside Assistance",
    "Driver Attention Monitoring",
    "Surround Sound System",
    "Internet Connectivity",
    "Voice Control",
    "Digital Instrument Cluster",
    "Heads-Up Display",
    "Rear Entertainment System",
    "Roof Rails",
    "Navigation with Voice Guidance",
    "Wi-Fi Hotspot",
    "Automatic Parking",
    "Power Sunshade",
    "Fold-Flat Rear Seats",
    "Adjustable Pedals",
    "Active Noise Cancellation",
    "Driver Profiles",
    "Underfloor Storage",
    "Hands-Free Liftgate",
    "High-Performance Brakes",
    "Sport Seats",
    "Advanced Airbag System",
    "Rear Spoiler",
    "Dual Exhaust",
    "Electric Parking Brake",
    "Carbon Fiber Trim",
    "Manual Transmission",
    "Adaptive Cruise Control with Stop-and-Go",
];