export const carModels: { [brand: string]: string[] } = {
    Toyota: [
        "Corolla",
        "Camry",
        "RAV4",
        "Highlander",
        "Tacoma",
        "Tundra",
        "Sienna",
        "Yaris",
        "4Runner",
        "Avalon",
      ],
      Honda: [
        "Civic",
        "Accord",
        "CR-V",
        "Pilot",
        "Odyssey",
        "Fit",
        "HR-V",
        "Ridgeline",
        "Insight",
        "Clarity",
      ],
      Ford: [
        "F-150",
        "Mustang",
        "Escape",
        "Explorer",
        "Fusion",
        "Edge",
        "Expedition",
        "Ranger",
        "Bronco",
        "Transit",
      ],
      Chevrolet: [
        "Silverado",
        "Malibu",
        "Equinox",
        "Camaro",
        "Traverse",
        "Colorado",
        "Blazer",
        "Impala",
        "Tahoe",
        "Suburban",
      ],
      Nissan: [
        "Altima",
        "Rogue",
        "Sentra",
        "Murano",
        "Titan",
        "Armada",
        "370Z",
        "Juke",
        "Frontier",
        "Pathfinder",
      ],
      Hyundai: [
        "Elantra",
        "Sonata",
        "Tucson",
        "Santa Fe",
        "Kona",
        "Palisade",
        "Accent",
        "Venue",
        "Kona Electric",
        "Ioniq",
      ],
      Kia: [
        "Optima",
        "Sorento",
        "Sportage",
        "Soul",
        "Forte",
        "Seltos",
        "Carnival",
        "Niro",
        "Stinger",
        "Telluride",
      ],
      Volkswagen: [
        "Jetta",
        "Passat",
        "Tiguan",
        "Atlas",
        "Golf",
        "Arteon",
        "Beetle",
        "ID.4",
        "ID.3",
        "Atlas Cross Sport",
      ],
      Subaru: [
        "Outback",
        "Forester",
        "Crosstrek",
        "Legacy",
        "Ascent",
        "Impreza",
        "WRX",
        "BRZ",
        "Solterra",
        "Tribeca",
      ],
      Mazda: [
        "Mazda3",
        "Mazda6",
        "CX-5",
        "CX-9",
        "MX-5 Miata",
        "CX-30",
        "Mazda2",
        "Mazda MX-30",
        "CX-50",
        "CX-70",
      ],
      Mitsubishi: [
        "Outlander",
        "Eclipse Cross",
        "RVR",
        "Lancer",
        "Pajero",
        "Mirage",
        "Galant",
        "ASX",
        "L200",
        "Delica",
      ],
      Peugeot: [
        "208",
        "308",
        "3008",
        "5008",
        "508",
        "Partner",
        "Traveller",
        "Rifter",
        "RCZ",
        "2008",
      ],
      Renault: [
        "Clio",
        "Captur",
        "Kadjar",
        "Koleos",
        "Megane",
        "Talisman",
        "Scenic",
        "Kangoo",
        "Trafic",
        "Alpine A110",
      ],
      Fiat: [
        "500",
        "Panda",
        "Tipo",
        "500X",
        "500L",
        "Punto",
        "Doblo",
        "Qubo",
        "Freemont",
        "Panda 4x4",
      ],
      Skoda: [
        "Octavia",
        "Kodiaq",
        "Karoq",
        "Superb",
        "Fabia",
        "Rapid",
        "Enyaq",
        "Citigo",
        "Scala",
        "Kamiq",
      ],
      Suzuki: [
        "Vitara",
        "Jimny",
        "Swift",
        "S-Cross",
        "Baleno",
        "SX4",
        "Alto",
        "Grand Vitara",
        "Ignis",
        "Across",
      ],
      Citroën: [
        "C3",
        "C4",
        "C5 Aircross",
        "C3 Aircross",
        "C4 Cactus",
        "Berlingo",
        "SpaceTourer",
        "C5",
        "DS3",
        "DS7 Crossback",
      ],
      Opel: [
        "Astra",
        "Insignia",
        "Grandland",
        "Mokka",
        "Crossland",
        "Zafira",
        "Vivaro",
        "Combo",
        "Adam",
        "Astra OPC",
      ],
      Vauxhall: [
        "Astra",
        "Corsa",
        "Insignia",
        "Grandland X",
        "Mokka X",
        "Crossland X",
        "Zafira",
        "Vivaro",
        "Combo",
        "Adam",
      ],
      SEAT: [
        "Ibiza",
        "Leon",
        "Ateca",
        "Tarraco",
        "Arona",
        "Alhambra",
        "Exeo",
        "Toledo",
        "Mii",
        "Córdoba",
      ],
      Mercedes: [
        "A-Class",
        "C-Class",
        "E-Class",
        "S-Class",
        "GLA",
        "GLC",
        "GLE",
        "GLS",
        "CLA",
        "SLC",
      ],
      BMW: [
        "3 Series",
        "5 Series",
        "7 Series",
        "X3",
        "X5",
        "X7",
        "Z4",
        "M3",
        "M5",
        "i4",
      ],
      Audi: ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "TT", "R8"],
      Lexus: ["ES", "RX", "NX", "GX", "LX", "IS", "LC", "LS", "UX", "CT"],
      Jaguar: [
        "XE",
        "XF",
        "XJ",
        "F-Pace",
        "E-Pace",
        "I-Pace",
        "F-Type",
        "X-Type",
        "S-Type",
        "XJ220",
      ],
      LandRover: [
        "Defender",
        "Discovery",
        "Range Rover",
        "Range Rover Sport",
        "Range Rover Velar",
        "Discovery Sport",
        "Evoque",
        "LR4",
        "LR3",
        "Freelander",
      ],
      Cadillac: [
        "CT4",
        "CT5",
        "CT6",
        "XT4",
        "XT5",
        "XT6",
        "Escalade",
        "XTS",
        "ATS",
        "CTS",
      ],
      Lincoln: [
        "Navigator",
        "Aviator",
        "Corsair",
        "MKZ",
        "Continental",
        "MKC",
        "MKT",
        "Zephyr",
        "Town Car",
        "LS",
      ],
      Volvo: [
        "S60",
        "S90",
        "XC40",
        "XC60",
        "XC90",
        "V60",
        "V90",
        "S40",
        "C30",
        "C70",
      ],
      Porsche: [
        "911",
        "Cayenne",
        "Macan",
        "Panamera",
        "Taycan",
        "Boxster",
        "Cayman",
        "918 Spyder",
        "944",
        "928",
      ],
      Infiniti: [
        "Q50",
        "Q60",
        "QX50",
        "QX55",
        "QX60",
        "QX80",
        "G37",
        "M37",
        "JX35",
        "FX35",
      ],
      Genesis: [
        "G70",
        "G80",
        "G90",
        "GV70",
        "GV80",
        "Essentia",
        "Mint",
        "X Concept",
        "G70 Shooting Brake",
        "G80 Sport",
      ],
      Acura: ["MDX", "RDX", "TLX", "ILX", "NSX", "RLX", "ZDX", "RSX", "CL", "TL"],
      AlfaRomeo: [
        "Giulia",
        "Stelvio",
        "4C",
        "Giulietta",
        "Spider",
        "Alfetta",
        "GTV",
        "159",
        "Brera",
        "MiTo",
      ],
      Maserati: [
        "Ghibli",
        "Quattroporte",
        "Levante",
        "Alfieri",
        "GranTurismo",
        "GranCabrio",
        "Kubang",
        "Mistral",
        "Biturbo",
        "Indy",
      ],
      Bentley: [
        "Continental GT",
        "Flying Spur",
        "Bentayga",
        "Mulsanne",
        "Arnage",
        "Brooklands",
        "Azure",
        "Speed 8",
        "Bentley Eight",
        "T-Series",
      ],
      RollsRoyce: [
        "Phantom",
        "Ghost",
        "Wraith",
        "Cullinan",
        "Dawn",
        "Silver Spirit",
        "Silver Shadow",
        "Silver Cloud",
        "Corniche",
        "Park Ward",
      ],
      AstonMartin: [
        "DB11",
        "Vantage",
        "DBS Superleggera",
        "Rapide",
        "DBX",
        "One-77",
        "Vanquish",
        "DB7",
        "V12 Vantage",
        "DB9",
      ],
      Bugatti : [
        "Type 35",
        "Type 57SC Atlantic",
        "EB110",
        "Veyron",
        "Veyron Super Sport",
        "Chiron",
        "Chiron Super Sport 300+",
        "Divo",
        "Centodieci",
        "La Voiture Noire",
        "Bolide",
        "Mistral",
        "TourBillion 2026"
      ],
      Koenigsegg : [
        "Agera",
        "Agera R",
        "Agera S",
        "Agera RS",
        "Agera Final Edition",
        "CC",
        "CC8S",
        "CCR",
        "CCX",
        "CCXR",
        "CCGT",
        "Gemera",
        "Jesko",
        "Jesko Absolut",
        "Jesko Attack",
        "CC850",
        "Chimera",
        "Regera",
        "One",
        "Quant Concept",
        "TFG",
        "Trevita"
      ],
      Ferrari: [
        "488",
        "Portofino",
        "812 Superfast",
        "F8 Tributo",
        "Roma",
        "LaFerrari",
        "California",
        "458 Italia",
        "GTC4Lusso",
        "F12berlinetta",
      ],
      Lamborghini: [
        "Huracan",
        "Aventador",
        "Urus",
        "Gallardo",
        "Egoista",
        "Sian",
        "Centenario",
        "Murcielago",
        "Reventon",
        "Miura",
      ],
      Rivian: [
        "R1T",
        "R1S",
        "Rivian RCV",
        "Rivian RCV 100",
        "Rivian RCV 150",
        "Rivian RCV 200",
        "Rivian RCV 250",
        "Rivian RCV 300",
        "Rivian RCV 350",
        "Rivian RCV 400",
      ],
      Lucid: [
        "Air",
        "Gravity",
        "Lucid Air Pure",
        "Lucid Air Touring",
        "Lucid Air Grand Touring",
        "Lucid Air Dream Edition",
        "Lucid Air Touring Performance",
        "Lucid Air Grand Touring Performance",
        "Lucid Air Pure Performance",
        "Lucid Air Touring Performance",
      ],
      Polestar: [
        "Polestar 1",
        "Polestar 2",
        "Polestar 3",
        "Polestar 4",
        "Polestar 5",
        "Polestar 6",
        "Polestar 7",
        "Polestar 8",
        "Polestar 9",
        "Polestar 10",
      ],
      NIO: [
        "ES8",
        "ES6",
        "EC6",
        "ES7",
        "ET7",
        "ET5",
        "NIO EP9",
        "NIO ES3",
        "NIO ES4",
        "NIO ES5",
      ],
      Xpeng: [
        "P7",
        "P5",
        "G3",
        "G3i",
        "Xpeng X",
        "Xpeng Y",
        "Xpeng Z",
        "Xpeng A",
        "Xpeng B",
        "Xpeng C",
      ],
      BYD: ["Tang", "Han", "Song", "Qin", "e6", "e5", "F3", "F0", "L3", "Yuan"],
      Fisker: [
        "Ocean",
        "Pear",
        "Alaska",
        "Fisker Karma",
        "Fisker EMotion",
        "Fisker Aliante",
        "Fisker Force E",
        "Fisker Project Ocean",
        "Fisker Surf",
        "Fisker PEAR",
      ],
      Canoo: [
        "Lifestyle Vehicle",
        "Pickup Truck",
        "Cargo Van",
        "Business Van",
        "Canoo MPDV",
        "Canoo Delivery Van",
        "Canoo Pickup",
        "Canoo Lifestyle Vehicle Premium",
        "Canoo MPDV Plus",
        "Canoo Van",
      ],
      LordstownMotors: [
        "Endurance",
        "Endurance XT",
        "Endurance Pro",
        "Endurance Cargo",
        "Endurance Van",
        "Endurance SUV",
        "Endurance Pickup",
        "Endurance Sport",
        "Endurance Utility",
        "Endurance Electric",
      ],
      TataMotors: [
        "Nano",
        "Indica",
        "Indigo",
        "Safari",
        "Harrier",
        "Hexa",
        "Tiago",
        "Tigor",
        "Altroz",
        "Nexon",
      ],
      Mahindra: [
        "Bolero",
        "XUV500",
        "Thar",
        "Scorpio",
        "KUV100",
        "Alturas G4",
        "Marazzo",
        "eVerito",
        "XUV300",
        "XUV700",
      ],
      GreatWallMotors: [
        "Haval H6",
        "Haval F7",
        "Haval F5",
        "Great Wall Wingle",
        "Great Wall Poer",
        "Haval H9",
        "Great Wall M4",
        "Great Wall M6",
        "Haval H2",
        "Great Wall V80",
      ],
      Geely: [
        "Emgrand",
        "Coolray",
        "Azkarra",
        "Binyue",
        "Tugella",
        "Geely Xingyue",
        "Geely Panda",
        "Geely Vision",
        "Geely Bo Yue",
        "Geely EC7",
      ],
      Chery: [
        "Tiggo 2",
        "Tiggo 3",
        "Tiggo 4",
        "Tiggo 5",
        "Tiggo 7",
        "Tiggo 8",
        "Chery Arrizo 5",
        "Chery Arrizo 7",
        "Chery Exeed TX",
        "Chery QQ",
      ],
      Proton: [
        "Saga",
        "Persona",
        "Exora",
        "X70",
        "X50",
        "Iriz",
        "Perdana",
        "Satria",
        "Wira",
        "Tiara",
      ],
      Perodua: [
        "Myvi",
        "Axia",
        "Bezza",
        "Aruz",
        "Alza",
        "Kancil",
        "Kembara",
        "Rusa",
        "Nissan 350Z",
        "Nissan Juke",
      ],
      Dacia: [
        "Duster",
        "Sandero",
        "Logan",
        "Dokker",
        "Lodgy",
        "Spring",
        "Sander",
        "Duster 4x4",
        "Logan MCV",
        "Lodgy Stepway",
      ],
      Lada: [
        "Vesta",
        "Granta",
        "Xray",
        "Niva",
        "4x4",
        "Priora",
        "Kalina",
        "Largus",
        "Niva Travel",
        "Niva Legend",
      ],
      UAZ: [
        "Patriot",
        "Hunter",
        "Pickup",
        "UAZ 452",
        "UAZ 3909",
        "UAZ 3163",
        "UAZ 3160",
        "UAZ 2360",
        "UAZ 39094",
        "UAZ 3741",
      ],
};