export const carTypes: string[] = [
    "Sedan",
    "Coupe",
    "Hatchback",
    "Convertible",
    "SUV (Sport Utility Vehicle)",
    "Crossover",
    "Wagon (Station Wagon)",
    "Minivan",
    "Pickup Truck",
    "Van",
    "Sports Car",
    "Luxury Car",
    "Hybrid",
    "Electric Vehicle (EV)",
    "Plug-in Hybrid Electric Vehicle (PHEV)",
    "Off-Road Vehicle",
    "Roadster",
    "Limousine",
    "Compact Car",
    "Subcompact Car",
    "Full-Size Car",
    "Mid-Size Car",
    "Grand Tourer (GT)",
    "Supercar",
    "Hypercar",
    "Classic Car",
    "Muscle Car",
    "Commercial Vehicle",
    "Fleet Vehicle",
    "Utility Vehicle",
    "Panel Van",
    "Cargo Van",
    "Recreational Vehicle (RV)",
    "Towing Vehicle",
    "Luxury SUV",
    "Performance SUV",
    "Cross-Country Vehicle",
    "Touring Motorcycle",
    "Adventure Motorcycle",
    "Sport Motorcycle",
    "Cruiser Motorcycle",
    "Dual-Sport Motorcycle",
    "Electric Scooter",
    "Moped",
    "ATV (All-Terrain Vehicle)",
    "Utv (Utility Task Vehicle)",
];